server:
  port: 9060
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wb?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wb
    password: wb
  servlet:
    multipart:
      max-file-size: 100MB      # 单个文件的最大大小
      max-request-size: 100MB   # 单个请求的最大大小（包含所有文件）      
  data:
    redis:
      host: localhost
      port: 6379
      database: 2
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  flyway:
    baseline-version: 1
fileserver:
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: waxberry

